

const APP_BUTTON_BLUE = "#2699FB";
const APP_GREEN = '#3c560b';

const APP_BUTTON_BLUE_FADE = "#8AC4F4";

const APP_BLUE_44 = "#4470b7";
const APP_BLUE_84 = "#84D1EA";

const APP_IMAGE_GREY = "#f1f0ed";
const APP_BORDER_GREY = "#cccccc";
const DARK_GREY = "#3a3a3a";
const APP_BORDER_GREY_70 = "#707070";
const APP_ICON_BLACK = "#000000";
const APP_ICON_WHITE = "#ffffff";
const APP_LIGHT_GREY = "#A6A6A6";
const APP_RED = "#D71818";
const APP_BOX_GREY = "#00000029";

export {
    APP_GREEN,APP_BUTTON_BLUE,APP_BUTTON_BLUE_FADE,APP_BLUE_44,APP_RED,
    APP_BLUE_84,APP_BORDER_GREY,APP_LIGHT_GREY,APP_ICON_BLACK,
    APP_ICON_WHITE,APP_BOX_GREY,APP_IMAGE_GREY,DARK_GREY,
    APP_BORDER_GREY_70
}